### PR TITLE
[WIP] implement graphQL API authentication using JWT

### PR DESCRIPTION
**Pull request by pradel**
Create a authenticate mutation that return a valid token containing the user id.
On each request check if auth header is here and decode it.

### CODE REVIEW

**Comment by sid88in** [comment]
very nice @pradel 

Can you please add some screenshots showing functional testing both on Local and Remote. For instance : 

1. Screenshots of authentication of graphql and graphiql endpoints.
2. Screenshots of how to generate the token (with commands) 
3. Description of this PR.

thanks
Sid

**Comment by pradel** [comment]
Will do that next week :)

**Comment by sid88in** [comment]
@pradel 

1. you also might want to look at https://github.com/chenkie/graphql-auth by https://github.com/chenkie and how it all fits in our framework. He gave a very nice talk in GraphQL Summit 2017.

2. Please rebase your PR with master.

3. Add your name/companies name (if you want) in the readme.

**Comment by pradel** [comment]
Thanks for the link it is very helpful. Do you want me to implement a directive to protect the graphql queries?

**Comment by sid88in** [comment]
@pradel it will def be interesting to explore directives but I will let @nikgraf take a call on this. Few things we are thinking about

1. We want the new user onboarding experience to be seamless and they should not get confused with authorization and authentication

2. There are multiple ways to implement the same i.e cognito or auth0 or something else. we are thinking of restructuring repo to give that flexibility to the user to choose what he wants. 

Having said that it will be good to have a generic auth framework and directives might be one way to go! Lets wait to hear back from @nikgraf (he is currently busy so response might be delayed).

P.S: Thanks for your great work. We love your contributions  👍 Can you please reach out to me on twitter sidg_sid and we can talk about next steps in detail.

thanks
Sid

**Comment by pradel** [comment]
Hey @sid88in it looks like I can't pm you on twitter

**Pull request closed without merging**
