### PR TITLE
Refactor to use Apollo Client

### PR DESCRIPTION
**Pull request by helfer**
Removed a bunch of stuff that's now unnecessary.

It works on my end, but I'm not very familiar with webpack, so HMR isn't working. Probably an easy fix though, for someone who knows it better than me.

### CODE REVIEW

**Comment by kevinold** [comment]
@helfer Nice work getting Apollo client integrated!  

The issue with HMR is one I see often where it does not work with Functional Stateless Components (https://github.com/gaearon/babel-plugin-react-transform/issues/57).

The issue you see with HMR does not work on the master branch if updating a FSC.

React Hot Loader 3 is supposed to fix this and someone has this working (https://github.com/dimagimburg/react-hot-loader-stateless-function-component-example), but I have yet to try in any of my projects.

**Comment by dreadjr** [comment]
What are the benefits of choosing Apollo vs relay? Have you seen one work better in production environments?

**Comment by CGreenburg** [comment]
I'm also wondering the same as @dreadjr

**Comment by helfer** [comment]
@dreadjr that's probably a question best asked in the GraphQL slack or on stackoverflow.

**Comment by dreadjr** [comment]
@helfer That is probably true in general but i was really interested in context of this project.

**Comment by nikgraf** [comment]
sorry for the delay, I was busy with a lot of other stuff, but will try to come back to this later this week or early next week …

**Comment by stubailo** [comment]
Hi, any updates on this? Let's get a boilerplate going with Apollo as well, I think that will be advantageous for a lot of people using Redux.

**Comment by dreadjr** [comment]
I was more curious about the choice in relation with this project. Although generally speaking I would be interested as well. Both clients make specific choices and as a reference implementation i am looking for any points that fueled the decision.

**Comment by stubailo** [comment]
I think Apollo is a better choice in general (especially for people getting started), while Relay might be better for some specific apps. It integrates better with various community tools for Redux and React, is more flexible for a variety of apps, has sophisticated dev tools, and more closely follows forward-looking best practices like avoiding dynamic query manipulation. The best option might be to have two starter kits for GraphQL with serverless, one for Relay and one for Apollo, since people might still prefer to use Relay.

Is there anything specific to this project which would inform choosing one library over another?

**Comment by helfer** [comment]
@stubailo What you wrote reads a bit ambiguously. I'm sure you meant to say that Apollo integrates better with community tools for Redux and React, right?

**Comment by nikgraf** [comment]
@helfer thanks again for your help! I really appreciate it. For some time I wasn't sure what's the best way to move forward and if we want to support a Apollo & Relay version.

I splitted the repo: this one was renamed to serverless-graphql-apollo and extracted the other to serverless-graphql-relay. I plan to invest a bit more into this repo over the next couple days.

@helfer did anything in Apollo change since you opened the PR that would require a major change?

**Comment by singlow** [comment]
@nikgraf I am trying project for first time, but it seems the latest commit removes the updateSchema.js that is referenced in the npm script which is the 3rd step in the install/setup process. `npm run update-schema` is no longer necessary? Or is there a new substitute?

**Comment by stubailo** [comment]
@singlow with Apollo that step is unnecessary. Sounds like we need to update the setup directions.

**Comment by nikgraf** [comment]
@singlow just updated the Readme

**Pull request merged**
