### PR TITLE
[WIP] Backend rds integration

### LINKED ISSUE #176: mysql and postgres integration

### PR DESCRIPTION
**Pull request by pradel**
Close #176 

This pull request add the amazon rds support to the repository.

I used knex(http://knexjs.org/) as client for querying sql because with it you can query mysql, sqlite, postgre etc .. (so it can work with all rds instances with knex).

- [x] Offline
- [ ] Production
- [ ] Documentation
- [x] Update Readme
- [ ] PR Screenshots and steps to make it work
- [x] Build Green

The rds directory is basically the same as dynamodb.
On local it will run a sqllite database.

In order to make it work:
- just run yarn as usual to install dependencies.
- create an amazon rds instance (open to the internet) and get the url, user and password for the connection.
- Edit the security.env.prod file and change the `DATABASE_URL` field with your connection url (eg: postgres://${username}:{password}@${endpoint):5432/${dbName}).
- now you can run `yarn deploy-prod` which will deploy the backend.

### CODE REVIEW

**Comment by sid88in** [comment]
@pradel this is freaking huge! thanks !

**Comment by sid88in** [comment]
would be great to integrate serverless aurora :dagger: 🙈

**Comment by pradel** [comment]
I think serverless aurora will work the same you will just have to add your endpoint as the database connection url and it should work. Will need to test it!

**Comment by pradel** [comment]
I added the steps to get started with this pr in the description.
So everything is working great on local, but I get some issues with lambda on production.
I am sure my connection url is good, I run the production migrations and I see that my tables where updated on rds. The problem looks like the connection timeout on lambda.
To debug I tried to run the lambda offline connected to the rds instance and it worked well.
So it is really a problem on production, I suspect a vpc configuration but it's really weird since on local I can access to my database..
Anyway if you guys have some ideas!

**Comment by sid88in** [comment]
@nikgraf any thoughts on how to fix it? I remember you talking about connection timeouts with lambda and rds?

**Comment by sid88in** [comment]
merging this PR.

**Pull request merged**
